### ISSUE TITLE
Bind helper not rendering data to the DOM

### ISSUE THREAD

**Issue by silverwind** [mateusmaso/handlebars.binding#11]
Maybe I'm doing it wrong, but It seems I cannot get data to render with the basic `bind` helper. Here's a standalone example which you can save to a file and open:

````html
<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>
<main></main>
<script src="https://unpkg.com/handlebars/dist/handlebars.js"></script>
<script src="https://unpkg.com/handlebars.binding/dist/handlebars.binding.js"></script>
<script id="template" type="text/x-handlebars-template">{{bind "foo"}}</script>
<script>
  const main = document.querySelector("main");
  const template = document.querySelector("#template");
  const context = {foo: 123};
  const html = Handlebars.compile(template.innerHTML)(context);

  console.log("html:", html);
  console.log("parsed:", Handlebars.parseHTML(html));
  main.innerHTML = html;
</script>
</body>
</html>
````

The resulting `hb-binding` element is rendered empy and the script logs
````
html: <hb-binding id="cf8f8059-51d1-3674-ae6b-da7ba4643844"></hb-binding>
parsed: Array [ #text "123" ]
````

I tried running `Handlebars.update()` after inserting it DOM, but it didn't help either. Any idea why the data is seen in `parseHTML`, but not actually added to the DOM?

**Comment by mateusmaso** [comment]
I see your problem. You should never use ```innerHTML``` to assign templates that use binding helpers because it will cause to recreate all the DOM objects again. Instead you must use the DOM objects created by the ```Handlebars.parseHTML(html)``` (which are listening for context changes) and then append these nodes to your destination element children with ```appendChild```.

```html
<!DOCTYPE html><html><head><meta charset="utf-8"></head><body>
<main></main>
<script src="https://unpkg.com/handlebars/dist/handlebars.js"></script>
<script src="https://unpkg.com/handlebars.binding/dist/handlebars.binding.js"></script>
<script id="template" type="text/x-handlebars-template">{{bind "foo"}}</script>
<script>
  const main = document.querySelector("main");
  const template = document.querySelector("#template");
  const context = {foo: 123};
  const html = Handlebars.compile(template.innerHTML)(context);
  const htmlDOM =  Handlebars.parseHTML(html) // create DOMs and add bindings

  console.log("html:", html);
  console.log("parsed:", htmlDOM);
  main.appendChild(htmlDOM[0]) // instead of main.innerHTML = html;
  
  context.foo = 321
  Handlebars.update()
</script>
</body>
</html>
```

**Comment by silverwind** [comment]
Thanks, that indeed works. I think this method of DOM insertion should be mentioned in the README. If you like, I can clean up this example and send you a pull request.

**Comment by mateusmaso** [comment]
I agree with you. It's not that clear what one should do after calling ```Handlebars.parseHTML(html)```. Right now I'll just mention it on the usage section, as I recall you were not the only one who had trouble with this. If you have any further issues with the docs let me know and I'll try to improve.
