### ISSUE TITLE
Not working with multiple Handlebars instances

### ISSUE THREAD

**Issue by Owlbertz** [mateusmaso/handlebars.binding#12]
Hi,

if I create dynamic Handlebars instances via `Handlebars.create()` and pass each to the handlebars.binding-function, it only works the first time.
For the second call the function returns an un-extended Handlebars instance which lacks the `parseHTML()`-function.

I guess the issue comes from https://github.com/mateusmaso/handlebars.binding/blob/afe695b2ef2a45cf0683c6c675765bb267d5b686/src/index.js#L30 which makes the function only invokable once. Maybe there is a way to get around this?

**Comment by mateusmaso** [comment]
Hi @Owlbertz, sorry for the waiting on this one. I wrote this library a long time ago so I may have missed this use case or wasn't expecting it to happen. I'll try to write a test for it and see why is behaving like that.

**Comment by Owlbertz** [comment]
I found out that returning `deps.Handlebars` in a `else`-branch for the `if`-statement I linked above seems to work, although I suppose that internally things are getting messed up with this. I believe you store the reference to the handlebars instance for a reason?

**Comment by mateusmaso** [comment]
Yes, I was storing the reference in a way that was not possible handling multiple hb instances. I had to refactor some code in order to fix that. Check out the new version. Hope it works out now.

**Comment by Owlbertz** [comment]
I installed the latest version to find the problem fixed. Thank you very much for the fast response.
