### ISSUE TITLE
Nested each-loops: Index does not work

### ISSUE THREAD

**Issue by Owlbertz** [mateusmaso/handlebars.binding#13]
In nested for loops, `index` seems to always reference the outer index and not the inner one.
`{{../index}}` is equal to `{{index}}` within the inner loop.

**Comment by mateusmaso** [comment]
Hmm, I'll have to check this one out. This library lacks tests for nested loops, specially using indexes. Thanks for the report and let me know any further issues. I'll get back on this soon, for now what you could do is providing objects with preloaded indexes as a workaround.

```javascript
var context = {
  list1: [
    {
      index: 0, 
      value: {
        list2: [
          index: 0,
          value: {}
        ]
      }
    }
  ]
}

var template = Handlebars.compile(`
  {{#each list1 var="item" bind=true}}
    {{item.index}}
    {{#each item.list2 var="nestedItem" bind=true}}
      {{nestedItem.index}}
    {{/each}}
  {{/each}}
`)

Handlebars.parseHTML(template(context));
```

**Comment by Owlbertz** [comment]
Yes, of course assigning indexes manually would solve the problem, but I am working with a highly dynamic structure that represents a menu in which menu items may contain sub menu items and so on - hence the nested loops.
I am looking forward to you finding a solution and will try to find a fix myself if I get the time.

**Comment by mateusmaso** [comment]
It was indeed a bug that was missing on the test coverage. I manage to fix the issue and just released a new version. Please update the library inside your project and let me know if you're still having issues.

**Comment by Owlbertz** [comment]
This issue is also fixed in the latest version, thanks a lot.
