### ISSUE TITLE
Handlebars.registerElement is not a function

### ISSUE THREAD

**Issue by predorock** [mateusmaso/handlebars.binding#6]
Hi, i am very interested about this repo, because data binding is a feature that i need in my handlebars app. But i was testing it and learning how to use it, and i got his problem.
```
Uncaught TypeError: Handlebars.registerElement is not a function(anonymous function) @ handlebars.binding.js:413Utils @ handlebars.binding.js:17(anonymous function) @ handlebars.binding.js:20
templates-bind.html:11 

Uncaught TypeError: Cannot read property 'templates/foo' of undefined(anonymous function) @ templates-bind.html:11

my code
```
   ```html
<html>
   <head>
	
	<script type="text/javascript" src="node_modules/handlebars/dist/handlebars.runtime.js"></script>
	<script type="text/javascript" src="node_modules/handlebars.binding/dist/handlebars.binding.js">      </script>

   </head> 
   <body>
```
```javascript
	   <script type="text/javascript">
	   var context = {foo: 123};
	   var template = Handlebars.templates["templates/foo"];
	   var nodes = Handlebars.parseHTML(template(context));

	   document.getElementsByTagName('body').appendChild(nodes);

	   context.foo = 321;

	   </script>
```
```html
   </body>
   </html> 
```

The paths are corrected, there's something that i am missing?
Thanks

**Comment by mateusmaso** [comment]
I've noticed that you have not included the ```handlebars.element.js``` lib before ```handlebars.binding.js``` which is a dependency described [here] (https://github.com/mateusmaso/handlebars.binding#dependencies)

you also should check if your browser already support mutation observers natively, if not try to include as well polymer's fallback lib ```observe.js```

check the links below and let me know if it works then:
[https://github.com/mateusmaso/handlebars.element] (https://github.com/mateusmaso/handlebars.element)
[https://github.com/Polymer/observe-js] (https://github.com/Polymer/observe-js)

I strongly recommend you check out ```htmlbars.js``` if you are still not dealing with ```handlebars.js``` legacy for solving data binding issues, then this repository might/should solve your problem.
