### ISSUE TITLE
Error if use "if" into "each"

### ISSUE THREAD

**Issue by MrBoriska** [mateusmaso/handlebars.binding#8]
My test template

```
{{#each items var="item" bind=true}}
    <h2>Item {{bind "index"}}: {{bind "item.name"}}</h2>
    {{#if "../foo" bind=true}}
        <h1>Hello {{../foo}}, {{../bar}}</h1>
    {{else}}
        <h1>Goodbye</h1>
    {{/if}}
{{/each}}
```

and my code:

```
// init data
var context = {
    foo: "foo_old",
    bar: "bar_old",
    items: [
        {name: "tom"},
        {name: "ben"}
    ]
};

var templateScript = $('#book').html();
var template = Handlebars.compile(templateScript);
var nodes = Handlebars.parseHTML(template(context))

$(document.body).prepend(nodes);

setTimeout(function() {
    context.foo = "";
    context.bar = "updated_bar";
    context.items.push({name:"Joch"});
    context.items[1].name = "Alex";
    context.items.splice(0,1); // it destroys the indexes, but removes the element. Bug?
}, 1000*5);

Platform.performMicrotaskCheckpoint();
```

if you run this code, the debugger displays an error: 

> Uncaught TypeError: Cannot read property '' of undefined

if you run this code with other template (without "if" into "each"):

```
{{#if "foo" bind=true}}
    <h1>Hello {{foo}}, {{bar}}</h1>
{{else}}
    <h1>Goodbye</h1>
{{/if}}
{{#each items var="item" bind=true}}
    <h2>Item {{bind "index"}}: {{bind "item.name"}}</h2>
{{/each}}
```

then the errors do not watch.(Besides indexes)

I'm doing something wrong, or is this a bug? Thank you in advance.

Sorry for my English. I am not a native speaker.

**Comment by luccasmaso** [comment]
+1

**Comment by mateusmaso** [comment]
hey, thanks for letting me know @MrBoriska

try removing the "../" for parent context, it should work fine since this library extends the item context inside #each with it's root context once you have defined an alias to access your item. For now, you should also avoid binding paths that contains "../" for parent navigation, we don't support this syntax yet.

**Comment by MrBoriska** [comment]
Yes. It works. Thanks for the quick response.

Library is very useful, so I will test and watch for updates.
