### ISSUE TITLE
binding inside #each

### ISSUE THREAD

**Issue by MrBoriska** [mateusmaso/handlebars.binding#9]
template:

```
{{#each items bind=true}}
    <h2>Item {{bind "index"}}: {{bind "name"}}</h2>
    <h1>
    {{#if "foo" bind=true}}
        Hello {{foo}}
    {{else}}
        Goodbye
    {{/if}}
    </h1>
{{/each}}
```

code:

```
var context = {
    items: [
        {name: "tom", foo: "a"},
        {name: "cat", foo: "b"}
    ]
};

var templateScript = $('#book').html();
var template = Handlebars.compile(templateScript);
var nodes = Handlebars.parseHTML(template(context))

$(document.body).prepend(nodes);

setTimeout(function() {
    
    // works
    context.items[0] = {name: "Alex", foo: ""};
    
    // don't works
    context.items[0].name = "Alex";
    context.items[0].foo = "";
}, 1000*5);
```

I think it is clear from the code, what is the problem. 

if use other template:
```
{{#each items var="item" bind=true}}
    <h2>Item {{bind "index"}}: {{bind "item.name"}}</h2>
    <h1>
    {{#if "item.foo" bind=true}}
        Hello {{item.foo}}
    {{else}}
        Goodbye
    {{/if}}
    </h1>
{{/each}}
```

then it works, but the error is visible in the console (both methods context changes):

> observe.js:753 Exception caught during observer callback: TypeError: Cannot read property 'appendChild' of null

**Comment by mateusmaso** [comment]
thanks for reporting this one, I was rarely using this case you've pointed out.. it is clearly a bug related to #each helper without an item alias ("var" attribute) defined. Please update to 0.1.9 and let me know if it works out now.

**Comment by mateusmaso** [comment]
btw, I recommend you to always declare an alias variable for #each item so it won't get accidentally conflicted with root context properties since we don't support binding with "../" yet. (and IMO it's better to read/understand as well)

**Comment by MrBoriska** [comment]
Thanks for fix. It works now:
```
context.items[0].name = "Alex";
context.items[0].foo = "";
```
But the error remained. An exception is thrown always, regardless of how context changed (inside #each).
> observe.js:753 Exception caught during observer callback: TypeError: Cannot read property 'appendChild' of null

**Comment by mateusmaso** [comment]
hmm, weird.. I'm working on it

**Comment by MrBoriska** [comment]
May be browser? I am use Chrome 48.0.2564.116 m

I will try to correct himself. Maybe I find out something.

**Comment by MrBoriska** [comment]
If add:
`if (!nodes[index - 1].parentNode) continue;`

at the beginning of cycle on handlebars.element(106 line). Than the error disappears))

**Comment by mateusmaso** [comment]
the error was deeper than I thought.. check out 0.2.0, I fixed this issue and also added more tests to prevent future bugs related to #each block bindings

**Comment by MrBoriska** [comment]
oh, you're probably tired of me)

here is how I see this error again:

I'm use my old template:
```
{{#each items var="item" bind=true}}
    <h2>Item {{bind "index"}}: {{bind "item.name"}}</h2>
    <h1>
    {{#if "item.foo" bind=true}}
        Hello {{item.foo}}
    {{else}}
        Goodbye
    {{/if}}
    </h1>
{{/each}}
```

and default context:
```
var context = {
    items: [
        {name: "tom", foo: "a"},
        {name: "cat", foo: "b"}
    ]
};
```

and now it work without errors:
`context.items[0] = {name: "Alex", foo: ""};`

but this is still causes the error (the same)
```
context.items[0].name = "Alex";
context.items[0].foo = "";
```

Btw, if you remove the "{{#if}}", then there is no error.

**Comment by mateusmaso** [comment]
I got this issue fixed now (as you can see: https://jsfiddle.net/mateusmaso/v6dvqwyz), check out the lastest version and thanks for reporting it again.

**Comment by MrBoriska** [comment]
Great! It worked. Thank you.
